# Generated by Django 4.1.7 on 2023-06-09 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mangasapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='manga_uuid',
        ),
    ]
